apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: autotunchi
  namespace: autotunchi
  labels:
    app.kubernetes.io/name: autotunchi
    app.kubernetes.io/component: ingress
  annotations:
    # Cert-Manager TLS automático
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # Traefik
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    # External-DNS (creará registro en Cloudflare automáticamente)
    external-dns.alpha.kubernetes.io/hostname: autotunchi.smartperu.tech
    external-dns.alpha.kubernetes.io/ttl: "120"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - autotunchi.smartperu.tech
      secretName: autotunchi-tls
  rules:
    - host: autotunchi.smartperu.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: autotunchi
                port:
                  number: 80
